sudo: false
language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
install:
  - "travis_retry npm install typings@^1.0.1"
  - "travis_retry npm install"
script:
  - "tests/run_ci.sh"
